### ISSUE TITLE
Remove TPU limitation

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#519] opened 2019-04-12 14:12 UTC
@alistairrogers and his group have been doing some work on the lack of evidence for TPU limitation not having enough evidence to support it's inclusion in ESMs (references to follow), following on from a series of papers on the subject including the one on CLM that @danicalombardozzi led (illustrating the large sensitivity to TPU parameters under high CO2 scenarios which is perhaps not justified by data, https://iopscience.iop.org/article/10.1088/1748-9326/aacf68/pdf). 

Given that TPU calculations are done for each leaf layer of each cohort at each timestep, we could potentially save a lot of computation by removing this altogether. 

I made a branch here with the TPU statements removed from the photosynthesis code. 
https://github.com/rosiealice/fates/tree/no_TPU

@alistairrogers and @walkeranthonyp, can you check that I'm doing the new smoothing calculations correctly, here?:
https://github.com/rosiealice/fates/blob/fc77a8b8103817a0ae37fc62a887bd2cd2efb94d/biogeophys/FatesPlantRespPhotosynthMod.F90#L1053

I'll try testing the impacts of this early next week, including the time savings...

If anyone wants to put up a defence of TPU limitation, please chime in!

**Comment by alistairrogers** [comment] 2021-02-05 19:21
Does that silence mean we can remove TPU? ;-) I have a paper in press that makes the case for removing the current model representation of TPU from TBMs. In a nutshell, there's very little evidence for TPU limitation in vegetation measured in their natural environment at current CO2, model artifacts exacerbate the importance of TPU, and the representation of TPU is based on several unconfirmed assumptions. Basically, it's not well represented and is impacting model output when it really shouldn't be doing so.

https://nph.onlinelibrary.wiley.com/doi/pdf/10.1111/nph.17092

**Comment by ckoven** [comment] 2021-02-05 19:35
I think 2 years (28 if you count 2020) is sufficient time for any TPU defenders to speak up. ;)  I merged @rosiealice's no_TPU branch up to the latest fates main branch here if you want to play with it (the merge didn't have any conflicts): https://github.com/ckoven/fates/tree/no_TPU_new

**Comment by rosiealice** [comment] 2021-02-10 08:00
Thanks @ckoven .  I'd totally forgotten that I did that.  
It might be worth @alistairrogers  or @walkeranthonyp  looking at the part where the quadratic terms are modified to make that it's doing what it should be doing? Around lin 1110 in:

https://github.com/NGEET/fates/compare/master...ckoven:no_TPU_new#diff-f62a39ba3dc682263ce52ac5f1bec68ac12bc849e5987c1a793938bb2a1339e8R1091

Also I don't think I've gone as far as actually taking the parameters out of th the input file (but that would need to be an API change and maybe thus bundling in with other such changes).

**Comment by walkeranthonyp** [comment] 2021-02-10 23:59
Apologies for the errr (2 years) late response 😬. I took a quick look and I think there's an issue with c4 limited photosynthesis in the new code. We want to keep the third (pepc) limiting rate for c4s. 

That means keeping the 2nd smoothing for c4s too. 

Also, while we're at it the smoothing parameter for c4 could also be reinstated. We don't know enough about that to say whether it should be removed and the 0.999 value gives c4s a big advantage. Also the lower smoothing param value may be used when estimating c4 photosynthetic parameters. Not sure.

**Comment by alistairrogers** [comment] 2021-02-12 17:25
@walkeranthonyp I was struggling to find the right part of the code for this, could you give me a line number. For C4 plants there is a steep initial slope in the response of A to CO2 (PEPC limited) then a very sharp transition to Rubisco/ PEP regeneration limited A. Typically C4 plants are Vmax limited or co-limited at current CO2. Is this the transition you are talking about if so I would argue that smoothing would not be consistent with observations - it's a very sharp transition and way sharper than the Vcmax/Jmax transitions in C3 which we've shown should be minimally smoothed - or not smoothed at all.

**Comment by walkeranthonyp** [comment] 2021-02-13 18:29
Sure. Assuming things have not changed, here's the old code:
https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90

And the new:
https://github.com/ckoven/fates/blob/no_TPU_new/biogeophys/FatesPlantRespPhotosynthMod.F90

Both starting around line 1070. The new code has only two limiting rates
for c4: vcmax and light limiting rates.

Fair play on the smoothing argument. Defo your wheelhouse. ... Leaves us
scratching our heads to figure out in fates why c4 photosynthesis is so
much better than c3 under practically all env conditions.

**Comment by ckoven** [comment] 2021-03-11 22:42
So @walkeranthonyp @alistairrogers is there a consensus decision then on whether to remove this for both C3 and C4, or just for C3? And do we want to do a hard removal versus putting in switches that let one turn it on and off to conduct experiments?

the current diffs for the two photosynthesis pathways being:
here for C3:
https://github.com/NGEET/fates/compare/master...ckoven:no_TPU_new#diff-f62a39ba3dc682263ce52ac5f1bec68ac12bc849e5987c1a793938bb2a1339e8L1094-L1096

here for C4:
https://github.com/NGEET/fates/compare/master...ckoven:no_TPU_new#diff-f62a39ba3dc682263ce52ac5f1bec68ac12bc849e5987c1a793938bb2a1339e8L1094-L1096

**Comment by ckoven** [comment] 2021-03-11 22:42
oops looks like those links didn't work, sorry.

**Comment by walkeranthonyp** [comment] 2021-03-13 13:16
I think the consensus is to remove TPU for C3.

For C4 the third limitation is not TPU limitation, so the third limitation
should stay.

I know that makes it awkward but I don't see another way. Unless you just
make tpu really high for c3, but that could be misleading in the future and
doesn't save any computation.

**Comment by ckoven** [comment] 2021-03-15 22:03
Hi @walkeranthonyp @alistairrogers I've updated the code in https://github.com/ckoven/fates/tree/no_TPU_new to now keep the pep-carboxylase-limited term for C4 but get rid of the TPU-limited for C3.  I moved the smoothing parts into the C3/C4 if statement block to avoid a second if statement (for speed, at least in principle). Also I've gotten rid of all the parameters that supported TPU limitation before.  Could you take a look and let me know if you see any other issues before I submit as a PR?

**Comment by walkeranthonyp** [comment] 2021-03-17 02:15
Looks good to me, nice one Charlie. Model simplification in action!

**Comment by ckoven** [comment] 2021-03-17 03:02
Great, thanks @walkeranthonyp!

**Comment by rgknox** [comment] 2021-03-17 16:39
those changes look good @ckoven

**Comment by ckoven** [comment] 2021-03-17 16:42
thanks @rgknox.  I'l run a quick test and submit a PR if it looks good.

**Closed** 2021-04-13 22:10 UTC
