### ISSUE TITLE
Do FATES reduced complexity modes need HLM compsets? 

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#629] opened 2020-04-05 14:31 UTC
On the call on Thursday, @dlawrenncar suggested that the reduced complexity FATES modes could be controlled by some sort of compset idea.  I didn't articulate my objection to that idea particularly well, and on reflection, I thought that having both HLM compsets AND FATES compsets on top of each other might get too unwieldy and confusing.  That combined with some sort of personal long held fear of compsets and their mysteries that I'm trying to work through...  ;) 

Thinking about this some more, it occurs to me that there might actually be a need for the FATES reduced complexity modes to be to some extent under the control of the HLM compsets themselves. Much of the heavy lifting wrt organizing the surface datasets, reading in the SP and BGC drivers, and determining that those things need to happe at all will be, under our current division of labour, a feature of the HLM.  Thus, it might be the best situation if we implemented something like the following in the HLM:

FATES (normal FATES mode with LAI and PFTs prognostic)
FATES_SP (reads in monthly gridded LAI drivers and tiled PFTs) 
FATES_SBG ('static biogeography' reads in tiled PFTs)
FATES_LU (reads in land use transitions) 

Now, one thing that I don't understand right now is how the SST mode currently gets the input it needs. Does it go straight into FATES or through the HLM interfaces?  It makes sense that those don't use HLM compsets, because the idea of these types of files is alien to the compset architecture at present. Is what happens there a good template for the other reduced complexity modes? 

I'm putting this 'issue' up mostly to start a discussion on the correct way to implement these things, so welcome input from FATES and CLM and ELM people (esp @rgknox @ckoven @glemieux @ekluzek @dlawrenncar @wwieder @bishtgautam @billsacks) on the general question of how best to control this behaviour efficiently. 

Slides here for reference: 
https://docs.google.com/presentation/d/1_z2PIroU0AzLgwHuDf-ast-OrLPpSiSzW-liLvH5vyo/edit?usp=sharing

**Comment by billsacks** [comment] 2020-04-06 16:20
@rosiealice thanks for starting this discussion. I don't have a lot of specific thoughts here, mainly because I haven't had the time or mental energy to really wrap my mind around all of the relevant details. But I will share my general mental model of compsets, in case it's useful. As with most mental models, this isn't 100% accurate, but I think it's close enough for this discussion.

In general, a compset is just a convenient way to set the initial / default set of xml variables in a case. Those xml variables, in turn, are just a convenient way to set the initial / default set of Fortran namelist variables (including pointing to the appropriate NetCDF input files).

As far as I know (correct me if I'm wrong), FATES doesn't have its own scripting infrastructure, but relies on the HLM for any pre-run setting of parameters, etc. So, in that sense, the question of how the default values for various FATES flags get set is up to the HLM. Once you get into FATES at runtime, FATES will just be reading individual namelist flags and NetCDF files – though it certainly makes sense for FATES to do some sanity checks to make sure the HLM hasn't given it incompatible values for certain flags.

That said, when I think about how to do this in CTSM, I do think of compsets. Perhaps the compset would set an xml variable like `FATES_MODE`, which would in turn set the default values for the individual FATES flags.

**Comment by glemieux** [comment] 2022-11-17 18:30
Closing out as we have started to create composts as needed (in this case regression testing).

**Closed by glemieux** 2022-11-17 18:30 UTC
